import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createApp} from '../server.js';
async function setup(t,options={}){const dataDir=await mkdtemp(path.join(tmpdir(),'chai-test-'));const app=await createApp({adminToken:'test-token',authMode:'local-token',dataDir,...options});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port;t.after(async()=>{await app.close();await rm(dataDir,{recursive:true,force:true});});return {app,url,dataDir};}
const cart={city:'Mumbai',items:[{id:'masala',quantity:2}]};
const post=(url,body)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const admin=(url,scenario)=>fetch(url+'/api/admin/scenario',{method:'POST',headers:{authorization:'Bearer test-token','content-type':'application/json'},body:JSON.stringify({scenario})});
const telemetry=async url=>(await fetch(url+'/api/admin/telemetry',{headers:{authorization:'Bearer test-token'}})).json();
test('checkout uses server prices, protects lookup and persists business events',async t=>{const {url,dataDir}=await setup(t,{gatewayDelay:1});const response=await post(url+'/api/checkout',{...cart,total:1});assert.equal(response.status,201);const order=await response.json();assert.equal(order.total,60);assert.equal((await fetch(url+'/api/orders/'+order.id)).status,404);assert.equal((await fetch(url+'/api/orders/'+order.id,{headers:{'x-order-token':order.lookupToken}})).status,200);assert.equal((await telemetry(url)).events.length,5);const second=await createApp({adminToken:'test-token',authMode:'local-token',dataDir});await new Promise(r=>second.server.listen(0,'127.0.0.1',r));const restored=await fetch('http://127.0.0.1:'+second.server.address().port+'/api/orders/'+order.id,{headers:{'x-order-token':order.lookupToken}});assert.equal(restored.status,200);await second.close();});
test('auth, malformed carts, missing pages and unknown scenarios',async t=>{const {url}=await setup(t);assert.equal((await fetch(url+'/api/admin/telemetry')).status,401);assert.equal((await post(url+'/api/admin/scenario',{scenario:'gateway-down'})).status,401);assert.equal((await post(url+'/api/checkout',null)).status,400);for(const items of [[],[{id:'bogus',quantity:1}],[{id:'masala',quantity:-1}],[{id:'masala',quantity:1.5}]])assert.equal((await post(url+'/api/checkout',{city:'Mumbai',items})).status,400);assert.equal((await fetch(url+'/chai-not-found')).status,404);assert.equal((await admin(url,'oops')).status,400);assert.equal((await fetch(url+'/api/checkout',{method:'POST',body:'{'})).status,400);});
test('pool exhaustion yields real waits, 504s and missing gateway spans; rollback restores checkout',async t=>{const {url}=await setup(t,{timeout:50,gatewayDelay:100});await admin(url,'pool-exhaustion');const replies=await Promise.all(Array.from({length:15},()=>post(url+'/api/checkout',cart)));assert.ok(replies.some(r=>r.status===504));const d=await telemetry(url);assert.equal(d.pool.active,0);assert.equal(d.pool.waiting,0);const failed=d.traces.find(x=>x.status===504);assert.ok(failed.spans.some(s=>s.name==='Pool.getConnection'&&s.status==='ERROR'&&s.duration>=45));assert.ok(!failed.spans.some(s=>s.service==='payfast-demo'));assert.ok(d.logs.some(l=>l.loglevel==='ERROR'));await admin(url,'healthy');assert.equal((await post(url+'/api/checkout',cart)).status,201);});
test('ERP outage queues invoices while commerce succeeds, recovery replays',async t=>{const {url}=await setup(t,{gatewayDelay:1});await admin(url,'erp-down');assert.equal((await post(url+'/api/checkout',cart)).status,201);let d=await telemetry(url);assert.equal(d.events.filter(e=>e.status==='queued').length,1);assert.equal(d.events.filter(e=>e.status==='completed').length,4);await admin(url,'healthy');d=await telemetry(url);assert.equal(d.events.filter(e=>e.status==='queued').length,0);});
test('gateway outage frees pool slots and recovery works',async t=>{const {url}=await setup(t,{gatewayDelay:1});await admin(url,'gateway-down');assert.equal((await post(url+'/api/checkout',cart)).status,504);assert.equal((await telemetry(url)).pool.active,0);await admin(url,'healthy');assert.equal((await post(url+'/api/checkout',cart)).status,201);});
test('Firebase-gated routes deny both telemetry and fault changes after admin removal',async t=>{let member=true;const {firebaseAuthorizer}=await import('../auth.js');const {url}=await setup(t,{authMode:'firebase',firebaseConfig:{apiKey:'public-test-key',authDomain:'example.firebaseapp.com',projectId:'example',appId:'public-app-id'},authorizer:firebaseAuthorizer({verifyIdToken:async()=>({uid:'u',email:'admin@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}}),hasAdmin:async()=>member})});const headers={authorization:'Bearer firebase-id-token','content-type':'application/json'};assert.equal((await fetch(url+'/api/admin/session',{headers})).status,200);member=false;assert.equal((await fetch(url+'/api/admin/telemetry',{headers})).status,403);assert.equal((await fetch(url+'/api/admin/scenario',{method:'POST',headers,body:JSON.stringify({scenario:'pool-exhaustion'})})).status,403);const config=await (await fetch(url+'/api/auth/config')).json();assert.equal(config.mode,'firebase');assert.equal(JSON.stringify(config).includes('firebase-id-token'),false);});
