import {test} from 'node:test';
import assert from 'node:assert/strict';
import {firebaseAuthorizer,createAuthorizer} from '../auth.js';
const user={uid:'admin-uid',email:'facilitator@example.test',email_verified:true,firebase:{sign_in_provider:'google.com'}};
const request={headers:{authorization:'Bearer signed-id-token'}};
test('verified Google user must be in Firestore admin list; membership checked on every call',async()=>{let checks=0,member=true;const authorize=firebaseAuthorizer({verifyIdToken:async(token,revoked)=>{assert.equal(token,'signed-id-token');assert.equal(revoked,true);return user;},hasAdmin:async email=>{assert.equal(email,user.email);checks++;return member;}});assert.equal((await authorize(request)).email,user.email);member=false;await assert.rejects(authorize(request),e=>e.status===403);assert.equal(checks,2);});
test('rejects missing, expired and revoked tokens',async()=>{const authorize=firebaseAuthorizer({verifyIdToken:async()=>{throw Object.assign(new Error('expired'),{code:'auth/id-token-expired'});},hasAdmin:async()=>true});await assert.rejects(authorize({headers:{}}),e=>e.status===401);await assert.rejects(authorize(request),e=>e.status===401);});
test('anonymous, unverified and non-Google identities cannot authorize',async()=>{for(const invalid of [{...user,email_verified:false},{...user,email:undefined},{...user,firebase:{sign_in_provider:'anonymous'}}]){let checked=false;const authorize=firebaseAuthorizer({verifyIdToken:async()=>invalid,hasAdmin:async()=>{checked=true;return true;}});await assert.rejects(authorize(request),e=>e.status===403);assert.equal(checked,false);}});
test('admin lookup outages fail closed; Firebase never falls back to shared token',async()=>{const authorize=firebaseAuthorizer({verifyIdToken:async()=>user,hasAdmin:async()=>{throw new Error('offline');}});await assert.rejects(authorize(request),e=>e.status===503);const unconfigured=await createAuthorizer({mode:'firebase',adminToken:'signed-id-token'});await assert.rejects(unconfigured(request),e=>e.status===503);});
